In [1]:
import numpy
numpy.__version__

'1.14.0'

# 파이썬의 데이터 타입 이해하기
파이썬 사용자는 대체로 파이썬의 사용 편의성에 끌리는데, 그중 하나가 동적 타이핑이다. C나 JAVA같은 정적 타입 체계를 가진 언어는 모든 변수를 명시적으로 선언해야 하지만, 파이썬처럼 동적 타입 체계를 가진 언어는 타입을 지정하지 않아도 된다. -40p

# 파이썬 정수는 정수 이상이다.
표준 파이썬은 C로 구현돼 있다. 이 말은 곧 모든 파이썬 객체가 그 값뿐만 아니라 다른 정보까지 포함하는 똑똑하게 위장한 C구조체라는 뜻이다. -41p

# 파이썬 리스트는 리스트 이상이다.

In [2]:
L = list(range(10))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
type(L[0])

int

In [4]:
L2 = [str(c) for c in L]
L2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [5]:
type(L2[0])

str

In [6]:
L3 = [True, "2", 3.0, 4]
[type(item) for item in L3]

[bool, str, float, int]

파이썬의 동적 타이핑 덕분에 서로 다른 데이터 타입의 요소를 담는 리스트를 만들 수도 있다.
그러나 이 유연성에는 비용이 따른다. 이렇게 유연한 타입을 허용하려면 리스트의 각 항목에 타입 정보와 참조 횟수, 기타 정보가 들어가야 한다.
고정 타입의 NumPy 스타일 배열은 이러한 유연성은 부족하지만 데이터를 저장하고 가공하기에는 훨씬 더 효율적이다. -43p

# 파이썬의 고정 타입 배열

In [7]:
import array
L = list(range(10))
A = array.array('i', L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

파이썬은 데이터를 효율적인 고정 타입 데이터 버퍼에 저장하는 다양한 방식을 제공한다.
그러나 훨씬 더 유용한 것은 NumPy 패키지의 ndarray 객체다.
파이썬의 array 객체는 배열 기반의 데이터에 효율적인 저장소를 제공하는 반면, NumPy는 그 데이터에 효율적인 연산을 추가한다. -44p

In [9]:
import numpy as np
np.array([1,4,2,5,3])

array([1, 4, 2, 5, 3])

In [10]:
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

파이썬 리스트와 달리 NumPy는 배열의 모든 요소가 같은 타입이어야 한다. 그래서 타입이 일치하지 않으면 상위 타입을 취하게 된다. -44p

In [11]:
np.array([1,2,3,4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [12]:
np.array([range(i, i+3) for i in [2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

파이썬 리스트와는 달리 NumPy 배열은 명시적으로 다차원 배열이 가능하다. -45p

# 처음부터 배열 만들기
규모가 큰 배열의 경우에는 NumPy에 내장된 루틴을 이용해서 처음부터 배열을 생성하는 것이 더 효율적이다. -45p

In [13]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [14]:
np.ones((3,5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [15]:
np.full((3,5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [17]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [18]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [19]:
# 0과 1사이의 난수로 채운 3X3배열 만들기
np.random.random((3,3))

array([[0.33982646, 0.29182875, 0.44308331],
       [0.26839365, 0.54041824, 0.49577719],
       [0.38823501, 0.10225307, 0.36067012]])

In [20]:
# 평균0, 표준편차1의 난수로 채운 3X3 배열 만들기
np.random.normal(0, 1, (3,3))

array([[ 0.80523082, -1.72923516, -0.96834807],
       [-0.42714357, -0.45628007,  0.92560484],
       [ 0.75252476, -0.8537537 ,  0.13878328]])

In [21]:
np.random.randint(0, 10, (3,3))

array([[6, 9, 0],
       [0, 8, 0],
       [3, 7, 4]])

In [22]:
# 3X3 단위 행렬 만들기
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
np.empty(3)

array([1., 1., 1.])