# NumPy 유니버셜 함수(UFuncs)

### 배열 산술 연산

In [2]:
import numpy as np

x = np.arange(4)
print("x = ", x)
print("x + 5 = ", x+5)
print("x - 5 = ", x-5)
print("x * 2 = ", x*2)
print("x / 2 = ", x/2)
print("x // 2 = ", x//2)

x =  [0 1 2 3]
x + 5 =  [5 6 7 8]
x - 5 =  [-5 -4 -3 -2]
x * 2 =  [0 2 4 6]
x / 2 =  [0.  0.5 1.  1.5]
x // 2 =  [0 0 1 1]


In [3]:
print("-x = ", -x)
print("x ** 2 = ", x**2)
print("x % 2 = ", x%2)

-x =  [ 0 -1 -2 -3]
x ** 2 =  [0 1 4 9]
x % 2 =  [0 1 0 1]


### 절댓값 함수

In [4]:
x = np.array([-2,-1,0,1,2])
abs(x)

array([2, 1, 0, 1, 2])

### 삼각함수

In [5]:
theta = np.linspace(0, np.pi, 3)

In [6]:
print("theta = ", theta)
print("sin(theta) = ", np.sin(theta))
print("cos(theta) = ", np.cos(theta))
print("tan(theta) = ", np.tan(theta))

theta =  [0.         1.57079633 3.14159265]
sin(theta) =  [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta) =  [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta) =  [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [7]:
x = [-1, 0, 1]
print("x = ", x)
print("arcsin(x) = ", np.arcsin(x))
print("arccos(x) = ", np.arccos(x))
print("arctan(x) = ", np.arctan(x))

x =  [-1, 0, 1]
arcsin(x) =  [-1.57079633  0.          1.57079633]
arccos(x) =  [3.14159265 1.57079633 0.        ]
arctan(x) =  [-0.78539816  0.          0.78539816]


### 지수와 로그

In [9]:
x = [1,2,3]
print("x = ", x)
print("e^x = ", np.exp(x))
print("2^x = ", np.exp2(x))
print("3^x = ", np.power(3, x))

x =  [1, 2, 3]
e^x =  [ 2.71828183  7.3890561  20.08553692]
2^x =  [2. 4. 8.]
3^x =  [ 3  9 27]


In [10]:
x = [1,2,4,10]
print("x = ", x)
print("ln(x) = ", np.log(x))
print("log2(x) = ", np.log2(x))
print("log10(x) = ", np.log10(x))

x =  [1, 2, 4, 10]
ln(x) =  [0.         0.69314718 1.38629436 2.30258509]
log2(x) =  [0.         1.         2.         3.32192809]
log10(x) =  [0.         0.30103    0.60205999 1.        ]


### 집계

In [11]:
x = np.arange(1, 6)
np.add.reduce(x)

15

In [13]:
np.multiply.reduce(x)

120

In [14]:
np.add.accumulate(x)

array([ 1,  3,  6, 10, 15], dtype=int32)

In [15]:
np.multiply.accumulate(x)

array([  1,   2,   6,  24, 120], dtype=int32)

### 외적

In [17]:
x = np.arange(1,6)
np.multiply.outer(x,x)

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])

### 출력 지정

In [18]:
x = np.arange(5)
y = np.empty(5)
np.multiply(x, 10, out=y)
print(y)

[ 0. 10. 20. 30. 40.]


In [19]:
y = np.zeros(10)
np.power(2, x, out=y[::2])
print(y)

[ 1.  0.  2.  0.  4.  0.  8.  0. 16.  0.]
