# NumPy 배열의 기초
여기서 소개하는 연산 유형이 다소 무미건조하고 현학적인 것처럼 보일 수 있지만, 이 책에 사용된 다른 많은 예제의 기초가 되니 잘 알아두자!

### 1. 배열 속성 지정

In [1]:
import numpy as np
np.random.seed(0)

x1 = np.random.randint(10, size=6)
x2 = np.random.randint(10, size=(3,4))
x3 = np.random.randint(10, size=(3,4,5))

In [2]:
x1

array([5, 0, 3, 3, 7, 9])

In [3]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [4]:
x3

array([[[8, 1, 5, 9, 8],
        [9, 4, 3, 0, 3],
        [5, 0, 2, 3, 8],
        [1, 3, 3, 3, 7]],

       [[0, 1, 9, 9, 0],
        [4, 7, 3, 2, 7],
        [2, 0, 0, 4, 5],
        [5, 6, 8, 4, 1]],

       [[4, 9, 8, 1, 1],
        [7, 9, 9, 3, 6],
        [7, 2, 0, 3, 5],
        [9, 4, 4, 6, 4]]])

In [5]:
# 차원의 개수
print("x1 ndim: ", x1.ndim)
print("x2 ndim: ", x2.ndim)
print("x3 ndim: ", x3.ndim)

x1 ndim:  1
x2 ndim:  2
x3 ndim:  3


In [6]:
# 각 차원의 크기
print("x1 shape: ", x1.shape)
print("x2 shape: ", x2.shape)
print("x3 shape: ", x3.shape)

x1 shape:  (6,)
x2 shape:  (3, 4)
x3 shape:  (3, 4, 5)


In [8]:
# 전체 배열의 크기
print("x1 size: ", x1.size)
print("x2 size: ", x2.size)
print("x3 size: ", x3.size)

x1 size:  6
x2 size:  12
x3 size:  60


In [9]:
print("dtype: ", x1.dtype)

dtype:  int32


In [10]:
# itemsize: 각 배열 요소의 크기
# nbytes: 배열의 전체 크기
print("itemsize: ", x1.itemsize, "bytes")
print("nbytes: ", x1.nbytes, "bytes")

itemsize:  4 bytes
nbytes:  24 bytes


### 2. 배열 인덱싱: 단일 요소에 접근하기

In [11]:
x1

array([5, 0, 3, 3, 7, 9])

In [12]:
x1[0]

5

In [13]:
x1[4]

7

In [14]:
x1[-1]

9

In [15]:
x1[-2]

7

In [16]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [17]:
x2[0,0]

3

In [18]:
x2[2,0]

1

In [19]:
x2[2,-1]

7

In [20]:
# 값 수정
x2[0,0] = 12

In [21]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [22]:
# NumPy 배열은 고정 타입을 가지기 때문에 뒤에 소수점이 잘림..!
x1[0] = 3.141592
x1

array([3, 0, 3, 3, 7, 9])

### 3. 배열 슬라이싱: 하위 배열에 접근하기

##### 1차원 하위 배열

In [23]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
x[:5]

array([0, 1, 2, 3, 4])

In [25]:
x[4:7]

array([4, 5, 6])

In [26]:
x[7:]

array([7, 8, 9])

In [27]:
x[::2]

array([0, 2, 4, 6, 8])

In [28]:
x[1::2]

array([1, 3, 5, 7, 9])

In [29]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [30]:
x[5::-2]

array([5, 3, 1])

##### 다차원 하위 배열

In [31]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [32]:
x2[:2, :3]

array([[12,  5,  2],
       [ 7,  6,  8]])

In [33]:
x2[:3, ::2]

array([[12,  2],
       [ 7,  8],
       [ 1,  7]])

In [34]:
x2[::-1, ::-1]

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]])

In [35]:
x2[:, 0]

array([12,  7,  1])

In [36]:
x2[0, :]

array([12,  5,  2,  4])

##### 사본이 아닌 뷰로서의 하위 배열
파이썬의 리스트 슬라이싱은 사본인 반면에 NumPy 배열 슬라이싱은 뷰이다.

In [37]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [38]:
x2_sub = x2[:2, :2]
x2_sub

array([[12,  5],
       [ 7,  6]])

In [39]:
x2_sub[0,0] = 99
x2_sub

array([[99,  5],
       [ 7,  6]])

In [41]:
# 뷰이기 때문에 원래 배열이 변경된 것을 볼 수 있다.
x2

array([[99,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

##### 배열의 사본 만들기

In [42]:
x2_sub_copy = x2[:2, :2].copy()
x2_sub_copy

array([[99,  5],
       [ 7,  6]])

In [43]:
x2_sub_copy[0,0] = 24
x2_sub_copy

array([[24,  5],
       [ 7,  6]])

In [44]:
# 사본을 만들어 사본을 수정했기 때문에 원래 배열의 값은 변함이 없다.
x2

array([[99,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

### 4. 배열 재구조화

In [45]:
grid = np.arange(1,10).reshape((3,3))
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [48]:
x = np.array([1,2,3])
x

array([1, 2, 3])

In [51]:
x.reshape((1,3))

array([[1, 2, 3]])

In [49]:
x[np.newaxis, :]

array([[1, 2, 3]])

In [50]:
x.reshape((3,1))

array([[1],
       [2],
       [3]])

In [52]:
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

### 5. 배열 결합 및 분할

##### 배열 연결

In [53]:
x = np.array([1,2,3])
y = np.array([3,2,1])
np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

In [54]:
z = [99, 99, 99]
np.concatenate([x,y,z])

array([ 1,  2,  3,  3,  2,  1, 99, 99, 99])

In [56]:
grid = np.arange(6).reshape((2,3))

In [57]:
grid

array([[0, 1, 2],
       [3, 4, 5]])

In [58]:
# 첫번 째 축을 따라 연결
np.concatenate([grid, grid])

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5]])

In [59]:
# 두번 째 축을 따라 연결
np.concatenate([grid, grid], axis = 1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [61]:
# 혼합된 차원의 배열로 작업할 때는 np.vstack과 np.hstack 함수를 사용하는 것이 더 명확하다.
x = np.array([1,2,3])
grid = np.array([[9,8,7],
               [6,5,4]])
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [62]:
y = np.array([[99], [99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

##### 배열 분할하기

In [63]:
x = [1,2,3,99,99,3,2,1]
x1, x2, x3 = np.split(x, [3,5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [64]:
grid = np.arange(16).reshape((4,4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [71]:
upper, lower = np.vsplit(grid, [3])

In [72]:
upper

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [73]:
lower

array([[12, 13, 14, 15]])

In [74]:
upper, lower = np.vsplit(grid, [2])

In [75]:
upper

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [76]:
lower

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [77]:
left, right = np.hsplit(grid, [2])

In [78]:
left

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [79]:
right

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])